const portfolioList = [
    {
        id: "moovit",
        type: "design",
        stack: "",
        stkimg: "",
        title: "moovit",
        description: "Projeto desenvolvido em parceira para com a Moovit que disponibilizou, em seu aplicativo oficial, um mapa das linhas de transporte em massa da região metropolitana do Rio.",
        image: "./assets/img/portfolio/008/image01.png",
        secondTitle: "rotas na palma da mão",
        secondDescription: "Disponível no app oficial da Moovit, o mapa visava facilitar a vida dos cariocas, dando uma visão detalhada das principais linhas de trem, metrô, brt, etc.",
        secondImage: "./assets/img/portfolio/008/image02.png",
        thirdTitle: "na mídia",
        thirdDescription: "O Jornal O Dia, um dos maiores da região, replicou uma matéria do Diário do Transporte, noticiando a disponibilização desse recurso em Maio de 2017, destacando a parceria entre a Moovit e a Karioka (minha marca, na época).",
        thirdImage: "./assets/img/portfolio/008/image03.png",
        fourthTitle: "do relevante ao essencial",
        fourthDescription: "O mapa destacava, inclusive, as estações que tinham recursos de acessibilidade, visando o conforto e bem estar dos usuários. O mapa ficou disponível durante mais de um ano, até sofrer alterações e ser substituído pelo mapa oficial da Prefeitura do Rio.",
        fourthImage: "./assets/img/portfolio/008/image04.png",
        link: "./assets/files/001.pdf"
    },
    {
        id: "karioka",
        type: "design",
        stack: "",
        stkimg: "",
        title: "karioka",
        description: "Estamparia com temática voltada para a cultura pop do Rio de Janeiro. Foi minha marca por mais de três anos, até o projeto da estamparia ser iniciado.",
        image: "./assets/img/portfolio/001/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando a silhueta do Pão de Açúcar em 'negative space' sobre o círculo azul, que representa o céu.",
        secondImage: "./assets/img/portfolio/001/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Letras desenhadas a partir de linhas e círculos.",
        thirdImage: "./assets/img/portfolio/001/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone15-3919TCX",
        fourthImage: "./assets/img/portfolio/001/image04.png",
        link: ""
    },
    {
        id: "horus",
        type: "design",
        stack: "",
        stkimg: "",
        title: "horus",
        description: "Consultoria em energia, eletricidade e serviços associados.",
        image: "./assets/img/portfolio/002/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando um olho e o bico de um falcão, imagem associada ao deus egípcio Horus.",
        secondImage: "./assets/img/portfolio/002/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Letras desenhadas a partir de linhas e círculos.",
        thirdImage: "./assets/img/portfolio/002/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone18-3838TCX",
        fourthImage: "./assets/img/portfolio/002/image04.png",
        link: ""
    },
    {
        id: "revoar",
        type: "design",
        stack: "",
        stkimg: "",
        title: "revoar",
        description: "Agência de turismo e eventos. O nome é uma analogia ao francês 'revoir', além de significar 'voar de novo' (re-voar).",
        image: "./assets/img/portfolio/003/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando a silhueta da Torre Eiffel, com dois pássaros em sobreposição aos andares da torre, como representação do nome.",
        secondImage: "./assets/img/portfolio/003/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Gruppo Regular",
        thirdImage: "./assets/img/portfolio/003/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone7557C, Pantone1807C, Pantone2727C",
        fourthImage: "./assets/img/portfolio/003/image04.png",
        link: ""
    },
    {
        id: "elevestebem",
        type: "design",
        stack: "",
        stkimg: "",
        title: "ele veste bem",
        description: "Blog de moda.",
        image: "./assets/img/portfolio/004/image01.png",
        secondTitle: "construção",
        secondDescription: "Listras verticais sobrepostas as silhuetas de uma barba e uma gravata borboleta, produtos de desenho digital/vetorial.",
        secondImage: "./assets/img/portfolio/004/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Josefin Sans Light",
        thirdImage: "./assets/img/portfolio/004/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "PantoneBlack7C, Pantone7671C",
        fourthImage: "./assets/img/portfolio/004/image04.png",
        link: ""
    },
    {
        id: "greencoast",
        type: "design",
        stack: "",
        stkimg: "",
        title: "greencoast",
        description: "Serviços em eletricidade, energia, projetos e manutenção.",
        image: "./assets/img/portfolio/005/image01.png",
        secondTitle: "construção",
        secondDescription: "Folha de árvore com nervura em formato de um transistor NPN, representando o ramo de atuação da empresas (energia, eletrônica e eficiência), aplicada em negativo a um círculo, produto de desenho digital/vetorial.",
        secondImage: "./assets/img/portfolio/005/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Exo 2 Light<br>Exo 2 Thin",
        thirdImage: "./assets/img/portfolio/005/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone7489C",
        fourthImage: "./assets/img/portfolio/005/image04.png",
        link: ""
    },
    {
        id: "carregadodeaxe",
        type: "design",
        stack: "",
        stkimg: "",
        title: "carregado de axé",
        description: "Loja virtual de artigos culturais e religiosos (projeto em andamento).",
        image: "./assets/img/portfolio/006/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos. As cores foram inspiradas na bandeira do Estado de Osún, na Nigéria.",
        secondImage: "./assets/img/portfolio/006/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Futurafrica Regular",
        thirdImage: "./assets/img/portfolio/006/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone7533C, Pantone7568C, Pantone7427C, Pantone7743C, Pantone7563C",
        fourthImage: "./assets/img/portfolio/006/image04.png",
        link: ""
    },
    {
        id: "convivencia",
        type: "design",
        title: "convivência",
        description: "Atêlie/projeto cultural formado por artistas portadores da Síndrome de Down.",
        image: "./assets/img/portfolio/007/image01.png",
        secondTitle: "construção",
        secondDescription: "Vetorização e colorização de arte feita por uma das integrantes do projeto.",
        secondImage: "./assets/img/portfolio/007/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "NovaMono Regular",
        thirdImage: "./assets/img/portfolio/007/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "#323F3C, #40534F, #557162, #698F70, #7FAF7F",
        fourthImage: "./assets/img/portfolio/007/image04.png",
        link: ""
    },
    {
        id: "bloco-de-notas",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "bloco de notas",
        description: `Bloco de notas com textos salvos em formato Markdown, com armazenamento das notas no Local Storage do navegador.`,
        image: "./assets/img/portfolio/goodbye31/15/project.png",
        secondTitle: "ferramentas",
        secondDescription: `JavaScript. Biblioteca 'Marked' para formatação do texto salvo. FontAwesome para ícones`,
        secondImage: "./assets/img/portfolio/goodbye31/js.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `O script interage diretamente com dois elementos do DOM: o botão 'Criar Nota' ('.add') e a div '.notes', que são declarados através do 'querySelector' como 'addButton' e 'notesContainer', respectivamente. Ao ser iniciado, o script verifica se há notas armazenadas no localStorage, através do método 'getItem' que executa um 'parse' no JSON e retornando-os em um array, caso positivo. Esse array é armazenado na constante 'notes' que é utilizada como condicional para executar um 'forEach' nela mesma executando, para cada nota, a função 'addNewNote' com essa nota como parâmetro. A função 'addNewNote' cria uma div com a classe 'note', através dos métodos 'createElement' e, posteriormente, 'classList.add'. Os elementos individuais do card são inclusos nela através do métodos 'innerHTML'. Após isso, quatro constantes são criadas, com o 'querySelector', para manipulação e edição da nota: 'markedText', a qual é atribuída a div '.main' onde é exibido o texto formatado; 'textEditor', a qual é atribuída a textarea onde o texto pode ser editado; 'editButton', a qual é atribuída o botão '.edit'; e 'deleteButton', a qual é atribuída o botão '.delete'. No 'editButton' é adicionado um Listener ('pointerdown') que o método 'classList.toggle' na 'markedText' e na 'textEditor', permitindo a transição entre o campo de edição e o texto salvo, além de usar esse mesmo método para substituir seu ícone (tag 'i'). A nota recebida no parâmetro da função é atribuída ao 'value' da 'textEditor' e ao 'markedText', com o 'innerHTML'. Um Listener ('input') é utilizado na 'textEditor', fazendo com que o valor substituído seja atribuído a 'markedText', com o 'innerHTML', além de executar a função 'updateLocalStorage()', que atualizada o storage com a nova nota. Na 'deleteButton' é usado um Listener ('pointerdown') que apaga a respectiva div através do método 'remove()', além de executar a função 'updateLocalStorage()', atualizando o storage, removendo a nota. A função 'addNewNote' é finalizada com o método 'appendChild' sendo utilizado na 'notesContainer', que faz com que a div criada seja adicionada como filha dela. A função 'updateLocalStorage', que atualiza os dados no storage, atribui um array com todas as textarea do documento a constante 'notesText' que é percorrida com um 'forEach', para que o valor de cada textarea seja incluso (.push()) no array 'notes', que é armazenado no storage através do método JSON.stringify. Por fim, um Listener ('pointerdown') no 'addButton' executa a função 'addNewNote', gerando um card em branco, habilitado para edição (classes dinâmicas no botão de edição, na div '.main' e na textarea fazem com que o card seja iniciado dessa maneira, caso a função 'addNewNote' seja executada com parâmetro vazio).`,
        thirdImage: "./assets/img/portfolio/goodbye31/15/project.png",
        fourthTitle: "projeto 15 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-quadro-desenho.now.sh/'
    },
    {
        id: "jogo-da-velha",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "jogo da velha",
        description: `Reprodução do clássico, com transição entre jogadores (X ou O) e histórico de jogadas com possibilidade de regressão.`,
        image: "./assets/img/portfolio/goodbye31/14/project.png",
        secondTitle: "ferramentas",
        secondDescription: `React. O 'helper.js', bem como as instruções para esse projeto, foram uma cortesia do canal 'codeSTACKr' no YouTube.`,
        secondImage: "./assets/img/portfolio/goodbye31/react.png",
        thirdTitle: "como funciona?",
        thirdDescription: `O componente 'Square' renderiza o 'value' recebido nas props em um botão, além de herdar o 'onClick' do componente 'Board'. O componente 'Board' usa a função 'map' no array 'squares' recebido nas props e, para cada item, renderiza um 'Square', passando para ele o 'value' correspondente a posição do array 'square' e o 'onClick' recebido nas props do componente 'Game'. No componente 'Game', a 'history' armazena o histórico de jogadas, sendo iniciada através do 'useState' como um array de 9 posições nulas. A 'stepNumber' armazena a posição da última jogada, relacionada ao histórico. 'xIsNext' indica qual é o próximo jogador, alternando entre 'true' e 'false'. A 'winner' usa o método 'calculateWinner' do 'helper.js' para verificar se, na condição atual, a mesa apresenta uma jogada vencedora, dentre as possíveis. 'xO' retorna a jogada (X ou O), testando a 'xIsNext' em um ternário. A função 'handleClick()', que é repassada para o 'Board' e o 'Square' através do 'onClick', recebe como parâmetro a posição da jogada, acrescentando-a a constante 'historyPoint' que é atribuída, com a 'stepNumber' como index, a constante 'current' que é armazenada, através de um spread operator, a constante 'squares'. É executada uma condicional que verifica se há um vencedor ('winner') ou se a posição clicada está preenchida (squares[index]). Caso não retorne positivo, a jogada é atribuída a posição correspondente (squares[index] = xO), o histórico é atualizado, bem como a posição da jogada atual nele, além da 'xIsNext' ter seu valor atribuído ao oposto. A função 'jumpTo()' retorna o quadro a jogada correspondente, armazenada na 'stepNumber', além de usar o próprio 'step' para verificar que era o jogador da vez, vendo se a chave da posição, dividida por 2, é par. A 'renderMoves()' renderiza o histórico, conforme as jogadas acontecem. Os botões gerados executam a 'jumpTo()'. No return principal, o componente 'Board' é renderizado, recebendo como 'squares' o histórico de jogadas.`,
        thirdImage: "./assets/img/portfolio/goodbye31/14/project.png",
        fourthTitle: "projeto 14 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-bloco-notas.now.sh/'
    },
    {
        id: "space-shooter",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "space shooter",
        description: `Jogo no estilo arcade compatível com PC (pelo teclado) e smartphones (pelos botões virtuais). O jogo é interrompido se o usuário perder as 10 energias, que são retiradas quando um alien consegue tocar a base do quadro do jogo.`,
        image: "./assets/img/portfolio/goodbye31/13/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Vue.js, JavaScript e CSS`,
        secondImage: "./assets/img/portfolio/goodbye31/vue.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Uma instância Vue foi criada na div '.wrapper', concentrando os dados do jogador (x, y, angle, bullets), do jogo (score, energy) e dos inimigos (enemies e enemyReached). Ao ser renderizada, ela executa os métodos 'updateBullet' e 'updateEnemy', através de 'created'. Nos métodos, 'rotateClockwise()' e 'rotateCounterClockwise()' alteram a variável 'angle', que afeta o player, através de um 'transform' aplicado nos estilos; o 'fire()' cria um novo bullet (com as posições e ângulo do jogador) no array 'bullets', que é afetado pelo 'updateBullet', que utiliza o objeto 'Math' para calcular o trajeto do disparo em função do ângulo do jogador, sendo interrompido e removi do array 'bullets', quando cai na condicional do método 'outOfScreen()', que verifica se o disparo saiu das coordenadas x e y da tela do jogo. O método 'checkCollision()' testa se um dos disparos e um dos inimigos estão na mesma posição. Caso positivo, um ponto é acrescentado em 'score' e o inimigo "atingido" é removido do array 'enemies'. O método 'enemyReachedBottom()' testa se um dos inimigos alcançou a base da tela, removendo-o do array 'enemies', trocando a condição de 'enemyReached' para 'true' e removendo um ponto de 'energy', seguido de um 'setTimeout' que retorna a condição de 'enemyReached' para 'false'. Essa variável é usada como teste em um ternário que acrescenta uma classe ao container do jogo, fazendo com que a tela dê uma leve chacoalhada, quando o jogador perde uma energia. O 'updateEnemy()' acrescenta um inimigo no array 'enemies', em posição aleatória no eixo x, usando um 'setInterval' que incrementa sua posição no eixo y, fazendo com que ele se mova pra baixo. Esse método executada o 'enemyReachedBottom()' para cada inimigo. Há um Listener no documento ('keydown), que captura entradas de teclas e, caso sejam as teclas jogáveis, executa os métodos correspondentes, descritos em tela.`,
        thirdImage: "./assets/img/portfolio/goodbye31/13/project.png",
        fourthTitle: "projeto 13 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-space-shooter.now.sh/'
    },
    {
        id: "quadro-de-desenho",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "quadro de desenho",
        description: `Quadro de desenho com variação de tamanho e cor do pincel.`,
        image: "./assets/img/portfolio/goodbye31/12/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: JavaScript`,
        secondImage: "./assets/img/portfolio/goodbye31/js.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `No HTML, o canvas tem medidas fixas a fim de evitar distorções no desenhos. Na barra abaixo, há três elementos que interagem com ele: um input do tipo 'range', que altera o tamanho do pincel (changeBrushSize()); um input do tipo 'color', que altera a cor utilizada (changeBrushColor()); e um botão que limpa o canvas (clearCanvas()). Os inputs enviam, como parâmetro, seu valor respectivo, que é aplicado as variáveis ('size' e 'color') utilizadas nas funções de desenho. O botão utiliza o método 'clearRect', do contexto, para limpar a tela. No canvas, foram inclusos quatro Listeners: para registrar a posição inicial de um traço ('pointerdown'); para interromper o traço e resetar a posição utilizada ('pointerup'); para detectar movimentos no touch e convertê-los para um evento de mouse ('touchmove'); e para detectar movimento do mouse ('mousemove') e, havendo toque/clique no trajeto, executar as funções de desenho: 'drawLine' e 'drawCircle', utilizadas em conjunto para gerar um traçado suave e com curvas, conforme as ações do usuário. A 'drawcircle' tem como parâmetro a posição (x,y) atual do ponteiro, desenhando círculos com diâmetro conforme valor do input e preenchidos com a cor selecionada, a cada ciclo da função. A 'drawLine' tem como parâmetro as posições (x,y) do início do toque (listener 'pointerdown') e do final do toque (listener 'pointerup'), traçando uma linha com a largura conforme valor do input e com a cor selecionada. As propriedades e métodos utilizados nas duas funções são nativas do método 'getContext' que foi atribuído em '2d' a constante 'context'.`,
        thirdImage: "./assets/img/portfolio/goodbye31/12/project.png",
        fourthTitle: "projeto 12 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-quadro-desenho.now.sh/'
    },
    {
        id: "galeria-de-imagens",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "galeria de imagens",
        description: `A aplicação utiliza a API do Unsplash, fazendo uma requisição customizada que retorna imagens conforme a busca selecionada. Clicando no card, o usuário é redirecionado a outra rota onde pode visualizar a imagem em resolução maior, podendo ainda clicar nela para abrir sua versão com resolução máxima, em outra aba. Layout feito com CSS Flexbox, responsivo e sem nenhum breakpoint.`,
        image: "./assets/img/portfolio/goodbye31/11/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: React, CSS Flexbox, API do Unsplash`,
        secondImage: "./assets/img/portfolio/goodbye31/react.png",
        thirdTitle: "como funciona?",
        thirdDescription: `A barra de busca tem como valor o estado 'query', que é atualizado através do atributo 'onChange' do input. No submit do formulário, essa query é aplicada ao endereço de requisição, retornando um conjunto de imagens correspondentes abaixo do formulário. Para abrir a imagem na visualização foram utilizadas duas Locations Props, uma com a imagem a ser exibida e outra com o array armazenado no estado 'images', para que ao voltar através do botão, o usuário possa ver a última busca que realizou: quando o App é montado, um hook de efeito verifica se há dados nas locations props, retornando a busca realizada, caso positivo, ou mantendo a página em branco, aguardando nova busca.`,
        thirdImage: "./assets/img/portfolio/goodbye31/11/project.png",
        fourthTitle: "projeto 11 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-galeria-reativa.now.sh/'
    },
    {
        id: "github-card",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "github card",
        description: `A página consome a API do GitHub através do 'axios', fazendo uma requisição a duas rotas, retornando um resumo dos dados do perfil buscado e a linguagem mais utilizada nos repositórios.`,
        image: "./assets/img/portfolio/goodbye31/10/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: Vue.js (Vue CLI), Semantic UI, API do GitHub`,
        secondImage: "./assets/img/portfolio/goodbye31/vue.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Quando a aplicação é iniciada, o componente GithubCard faz uma requisição a API, através de seu hook 'created', retornando os dados do perfil, que são armazenado no objeto 'user', além dos dados dos repositórios desse perfil, que são percorridos, com o método 'map', e tem as linguagens utilizadas armazenadas no array languageList, que é usado como parâmetro para o método 'findMostFrequentLanguage' do componente, que usa os métodos 'reduce' e 'filter' para comparar a recorrência das linguagens e retornar a que é mais utilizada. Quando uma busca é realizada, a 'searchKey' da instância principal é incrementada e, sendo passada como prop do componente GithubCard, atua como watcher, refazendo todos os passos, desde a requisição até a atribuição dos novos dados.`,
        thirdImage: "./assets/img/portfolio/goodbye31/10/project.png",
        fourthTitle: "projeto 10 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-github-resume-card.now.sh/'
    },
    {
        id: "app-meditacao",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "app de meditação",
        description: `App para auxiliar a meditação, com dois temas ambientes (e vídeos de fundo correspondentes), três opções de duração e botão play/pause com relógio regressivo.`,
        image: "./assets/img/portfolio/goodbye31/09/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: JavaScript`,
        secondImage: "./assets/img/portfolio/goodbye31/js.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Os elementos do DOM são capturados no script através do método 'querySelector', além de declaradas a medida da circunferência do círculo animado ao redor do play (outlineLength) e o tempo de duração da aplicação em modo play (fakeDuration). Para mudar o tema ambiente, utiliza-se um forEach nos botões capturados e atribui-se um Event Listener (pointerdown) para cada um, que altera as sources do video e do som, através dos atributos 'data-video' e 'data-sound' nos elementos HTML. Para mudar o tempo, também é utilizado um forEach nos botões, seguidos de Listeners (pointerdown) que alteram a 'fakeDuration', através do atributo 'data-time' nos elementos, além de alterar o texto do relógio regressivo. No botão play, também há um Event Listener (pointerdown), que executa a função 'checkPlaying()', verificando se o som está pausado ou em execução, tomando a ação correspondente com o vídeo de fundo, o som selecionado e o ícone do botão, que alterna entre play e pause. Por último, é executado o método 'ontimeupdate', no elemento de áudio, que decrementa o relógio, anima o círculo ao redor do botão e retorna o app ao estado original quando a 'fakeDuration' é menor que o tempo de execução, com vídeo e áudio pausados e botão habilitado como play.`,
        thirdImage: "./assets/img/portfolio/goodbye31/09/project.png",
        fourthTitle: "projeto 9 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-app-meditacao.now.sh/'
    },
    {
        id: "editor-de-fotos",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "editor de fotos",
        description: `Editor de fotos que permite carregar uma imagem PNG ou JPG e aplicar filtros CSS nela, com a opção de exportação do canvas onde a imagem foi editada.`,
        image: "./assets/img/portfolio/goodbye31/08/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com React`,
        secondImage: "./assets/img/portfolio/goodbye31/react.png",
        thirdTitle: "como funciona?",
        thirdDescription: `No cabeçalho, quando uma imagem é selecionada, uma função é executada através do atributo 'onChange' do input, que reseta os valores de configuração padrão (atribuindo a constante 'defaultValues' ao estado 'adjustedValues') e gera uma url temporária para a imagem que renderiza na 'img' abaixo do header. Essa imagem recebe os estilos através de um hook de efeito, que atualiza uma template com a propriedade filter e todos os valores aplicáveis através dos controles abaixo, vindos do estado 'adjustedValues'. Nos controles, os botões mudam o estado 'valuesIndex' que é utilizado para acessar os valores individuais da 'adjustedValue'. Quando o input range é alterado, o filtro selecionado nos botões é aplicado através do atributo 'onChange' desse input. Para a exportação, foi utilizada a dependência 'html-to-image', que imprime o canvas com os filtros aplicados em uma imagem JPEG.`,
        thirdImage: "./assets/img/portfolio/goodbye31/08/project.png",
        fourthTitle: "projeto 8 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-editor-de-fotos.now.sh/'
    },
    {
        id: "painel-drag-and-drop",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "painel drag and drop",
        description: `Painel no estilo kan ban, com três estados para as atividades, que podem ser incluídas através do formulário do cabeçalho e movidas de um quadro para o outro.`,
        image: "./assets/img/portfolio/goodbye31/07/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: Vue.js (Vue CLI) e CSS Flexbox`,
        secondImage: "./assets/img/portfolio/goodbye31/vue.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `O formulário do topo usa um input com v-model para a variável 'newCard' que é adicionada, através do método 'addCard()' ao array 'cards', que é renderizado no primeiro quadro, através da diretiva v-for. Quando um card é selecionado, sua ID é armazenada no Local Storage e seu display é alterado para 'none', através de um método no componente 'Card'. Quando o usuário solta o card em um quadro, um método do componente 'Board' é executado, utilizando a ID armazenada no Local Storage para assumir o card como filho, através do método 'appendChild()'. `,
        thirdImage: "./assets/img/portfolio/goodbye31/07/project.png",
        fourthTitle: "projeto 7 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-painel-drag-and-drop.now.sh/'
    },
    {
        id: "pomodoro-timer",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "pomodoro timer",
        description: `A aplicação permite a customização dos tempos de foco e de pausa, individualmente. É possível iniciar e pausar o timer, além de reiniciar a página ao estado original.`,
        image: "./assets/img/portfolio/goodbye31/06/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: JavaScript e CSS Flexbox`,
        secondImage: "./assets/img/portfolio/goodbye31/js.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Os elementos de texto dos timers, os botões e os inputs do tempo são selecionados no JavaScript com o método 'querySelector'. Os botões executam funções através de Event Listeners que resetam (botão Reset) a página, além de iniciar (botão Iniciar) ou interromper (botão Pausar) a função 'timer', que executa uma série de condicionais nas propriedades 'innerText' dos elementos de texto, realizando o decremento adequado a funcionalidade de timer, manipulando diretamente os dados dos elementos no DOM. Ao fim dos ciclos de foco e pausa, é exibido um alerta ao usuário, para que ele possa dar sequência ao próximo ciclo. Finalizados os dois, é feito um incremento no contador de ciclos.`,
        thirdImage: "./assets/img/portfolio/goodbye31/06/project.png",
        fourthTitle: "projeto 6 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-pomodoro-timer.now.sh/'
    },
    {
        id: "app-clima",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "app de clima",
        description: `Utilizando a API da OpenWeatherMap, a aplicação permite buscar o clima atual em qualquer local do mundo, através da barra de busca, exibindo um resultado com aparência dinâmica que varia conforme a condição do clima e a temperatura do local buscado.`,
        image: "./assets/img/portfolio/goodbye31/05/project.png",
        secondTitle: "ferramentas",
        secondDescription: `React. CSS Flexbox. API da OpenWeatherMap`,
        secondImage: "./assets/img/portfolio/goodbye31/react.png",
        thirdTitle: "como funciona?",
        thirdDescription: `Quando o usuário busca um local na barra de busca, a aplicação faz uma requisição a API, retornando os dados para exibição. Na renderização do container do app, são feitas verificações condicionais que retornam até nove variações de ícones conforme o clima e duas baseadas na temperatura. Após verificação, são aplicadas as classes correspondentes ao resultado obtido através da API.`,
        thirdImage: "./assets/img/portfolio/goodbye31/05/project.png",
        fourthTitle: "projeto 5 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-weather-app-react.vercel.app/'
    },
    {
        id: "lista-de-compras",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "lista de compras",
        description: `Loja do Mago, um shopping fake que vende itens e habilidades para desenvolvedores. Construído com VueJs, foi feita para explorar conceitos de reatividade, renderização condicional, binding, entre outros recursos como a criação e utilização de métodos na instância utilizada.`,
        image: "./assets/img/portfolio/goodbye31/04/project.png",
        secondTitle: "ferramentas",
        secondDescription: `VueJs - Scripts e renderização e CSS Flexbox`,
        secondImage: "./assets/img/portfolio/goodbye31/vue.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Uma instância Vue foi criada no elemento '#shopping-list', que contempla todos os itens da aplicação. Em seu estado 'default', a lista de itens da loja está oculta, sendo exibido apenas os itens selecionados (ou uma mensagem de carrinho vazio, caso nenhum item tenha sido escolhido na lista). Quando o botão 'Ver Loja' é clicado, o estado da instância é alterado para 'edit', exibindo os produtos disponíveis acima do resultado da loja. Clicando em 'comprar', o item selecionado é adicionado na lista de compras e tem sua classe e botão alterados, impedindo a inserção duplicada, através de um bind que verifica sua propriedade 'purchased', um booleano. Quando o botão remover é clicado, ele é removido da lista e volta ao seu comportamento e aparência padrão. Na lista de compras, havendo presença de itens selecionados, surge um botão 'finalizar' que direciona o usuário a um novo estado ('finished') que exibe uma mensagem de pedido finalizado.`,
        thirdImage: "./assets/img/portfolio/goodbye31/04/project.png",
        fourthTitle: "projeto 4 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-lista-de-compras-vuejs.now.sh/'
    },
    {
        id: "calculadora-javascript",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "calculadora",
        description: `Calculadora simples, criada com HTML, CSS e JavaScript.`,
        image: "./assets/img/portfolio/goodbye31/03/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: JavaScript, para validações de entradas de dados. Biblioteca math.js, que calcula a expressão exibida na tela. CSS Grid, para distribuir e organizar o layout da tela e dos botões.`,
        secondImage: "./assets/img/portfolio/goodbye31/js.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Os dados digitados são armazenados e exibidos em uma 'textarea' (tela da calculadora) alterando o 'value' do elemento. Quando um número é digitado, é feita uma validação (através da função inputNumber()), que verifica se o conteúdo na tela é o resultado de uma expressão recém-calculada. Caso positivo, o número substitui o resultado, iniciando uma nova expressão. Caso contrário, como na presença de um número seguido de um operador, o número é inserido dando continuidade a expressão. Para a inclusão de um operador, é feita uma outra validação (através da função inputOperator()) que evita a inserção seguida de mais de um operador. O botão 'C' executa a função clearScreen() que reseta a calculadora para seu estado inicial. O botão '=' executa a função displayResult(), que utiliza o método 'evaluate()' da biblioteca Math.js, para transformar a string com os números e operadores em uma expressão, retornando seu resultado, além de informar que o conteúdo na tela é um resultado, reiniciando a primeira validação.`,
        thirdImage: "./assets/img/portfolio/goodbye31/03/project.png",
        fourthTitle: "projeto 3 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-calculadora-javascript.now.sh/'
    },
    {
        id: "gerador-de-flexbox",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "gerador de flexbox",
        description: `Aplicação criada para demonstrar o comportamento de um flex-container, através da alteração de suas propriedades. A tela é dividida em duas partes (horizontalmente, no desktop, e verticalmente, nas telas menores), sendo metade para um "controller", onde você pode alterar as propriedades do container através dos respectivos 'select', e a outra para um preview do container e o código CSS gerado pelo controller.`,
        image: "./assets/img/portfolio/goodbye31/02/project.png",
        secondTitle: "ferramentas",
        secondDescription: `Criado com: ReactJS / Create React App. React HTML Parser, para exibir o código CSS com quebra de linha. E muuuuuito Flexbox <3 . Criado com 'create-react-app', pode ser executada e enviada para a produção com os scripts padrão, descritos no README da pasta, no repositório do desafio`,
        secondImage: "./assets/img/portfolio/goodbye31/react.png",
        thirdTitle: "como funciona?",
        thirdDescription: `No controller, cada 'select' altera (através da 'onChange') uma propriedade (aplicada com spread operator) a um objeto armazenado em um estado (criado com 'useState') em sintaxe JavaScript. Esses estilos são aplicados ao container do preview através de sua propriedade 'style'. Esse objeto é percorrido, dentro de um hook de efeito, e retorna um array com as propriedades (que são reescritas de camelCase para kebab-case, através do método 'replace()') e seus valores, quando não forem padrão, concatenando os textos no formato CSS, que é impresso na tela, com quebra de linha, utilizando o React HTML Parser.`,
        thirdImage: "./assets/img/portfolio/goodbye31/02/project.png",
        fourthTitle: "projeto 2 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-flexbox-generator.vercel.app/'
    },
    {
        id: "chat-em-tempo-real",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "chat em tempo real",
        description: "A aplicação foi criada importando o unpkg do Vue e abstraindo os scripts em um arquivo JS. Demais recursos foram importados através de links, no próprio HTML.",
        image: "./assets/img/portfolio/goodbye31/01/project.png",
        secondTitle: "ferramentas",
        secondDescription: "Criado com VueJs (Scripts e renderização), Firebase (realtime storage) e Native Toast (notificação)",
        secondImage: "./assets/img/portfolio/goodbye31/vue.jpg",
        thirdTitle: "como funciona?",
        thirdDescription: `Dentro da instância Vue, foram criados os dados a serem utilizados na aplicação, bem como os métodos que manipulam esses dados e interagem com o storage. A comunicação em tempo real com o storage do Firebase, através dos seus métodos nativos, fica dentro do hook 'created', que é executado a cada nova renderização da aplicação, além de atualizar as informações na tela através dos dados recebidos do storage, mantendo o chat com um ótimo tempo de resposta.`,
        thirdImage: "./assets/img/portfolio/goodbye31/01/project.png",
        fourthTitle: "projeto 1 de 31",
        fourthDescription: `Pra celebrar minha transição para os 32 anos, em novembro de 2020, iniciei o Goodbye.31, um desafio que se consiste em construir uma aplicação web todo dia, por 31 dias.`,
        fourthImage: "./assets/img/portfolio/goodbye31/goodbye31.jpg",
        link: 'https://g31-chat-vue-firebase.now.sh/'
    },
    {
        id: "iza",
        type: "código",
        stack: "CSS3",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original.svg",
        title: "iza",
        description: "Fanpage criada com HTML e CSS, utilizando técnicas de CSS Grid e Flexbox, tornando a página totalmente responsiva em diferentes dispositivos.",
        image: "./assets/img/portfolio/015/image01.jpg",
        secondTitle: "discografia",
        secondDescription: "Desde álbuns de estúdios a singles e participações, o site conta com o acervo da cantora, com links para as principais plataformas de streaming.",
        secondImage: "./assets/img/portfolio/015/image02.jpg",
        thirdTitle: "videografia",
        thirdDescription: "A videografia da cantora também está disponível na página, redirecionando o usuário através de um link para o do canal oficial no YouTube.",
        thirdImage: "./assets/img/portfolio/015/image03.jpg",
        fourthTitle: "redes sociais",
        fourthDescription: "A página conta também com os links para as redes sociais da Iza, bem como para seus perfis nas plataformas de streaming.",
        fourthImage: "./assets/img/portfolio/015/image04.jpg",
        link: 'https://iza.now.sh/'
    },
    {
        id: "pedra-papel-tesoura",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "pedra, papel, tesoura",
        description: "Jogo criado durante o Dev Day da Digital Innovation, através das aulas do Rafael Maia, utilizando Vue e Sass, além de recursos como responsividade e um local storage para armazenar a pontuação",
        image: "./assets/img/portfolio/016/image01.jpg",
        secondTitle: "conceito",
        secondDescription: "O jogo é uma variação do clássico Pedra, Papel e Tesoura, com o acréscimo de duas novas jogadas: Lagarto e Spock, que minimizam as chances de empate. Na tela inicial, você conta com os links para jogar e para ver as regras",
        secondImage: "./assets/img/portfolio/016/image02.jpg",
        thirdTitle: "regras",
        thirdDescription: "As regras originais se mantém com uma única diferença: nessa versão, cada jogada pode vencer ou perder de outras duas.",
        thirdImage: "./assets/img/portfolio/016/image03.jpg",
        fourthTitle: "jogabilidade",
        fourthDescription: "O gameplay é descomplicado possibilitando jogadas consecutivas em uma tela com design minimalista e interativo, que garante bons momentos de diversão.",
        fourthImage: "./assets/img/portfolio/016/image04.jpg",
        link: 'https://pptls.now.sh/'
    },
    {
        id: "rmgeradores",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "rm geradores",
        description: "Site institucional da RM Geradores, criado em formato 'one page layout'. A ideia por trás desse trabalho visava criar algo que fosse funcional e passasse uma mensagem rápida e direta, sem tomar muito tempo dos clientes.",
        image: "./assets/img/portfolio/014/image01.png",
        secondTitle: "dinâmico",
        secondDescription: "A seção de serviços conta com um script que exibe de forma dinâmica as informações referentes a cada tópico, sem a necessidade de redirecionar o cliente para outra(s) página(s).",
        secondImage: "./assets/img/portfolio/014/image02.png",
        thirdTitle: "call to action",
        thirdDescription: "Indo contra o usual do segmento, que costuma usar textos estáticos para as informações de contato, a RM conta com botões funcionais que levam os visitantes em contato direto com a equipe.",
        thirdImage: "./assets/img/portfolio/014/image03.png",
        fourthTitle: "mobile-first",
        fourthDescription: "A página foi criada com os princípios de 'mobile-first, para que o uso dela fosse otimizado em dispositivos móveis, melhorando a usabilidade e a experiência dos clientes, parceiros e colaboradores.",
        fourthImage: "./assets/img/portfolio/014/image04.png",
        link: 'https://rmgeradores.com.br/'
    },
    {
        id: "dragonflix",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "dragonflix",
        description: "Projeto criado durante a #ImersãoReact da Alura, que consiste-se em um acervo de vídeos do YouTube escolhidos pelo usuário. Criei o Dragonflix, uma coletânea de vídeos de rock e metal.",
        image: "./assets/img/portfolio/012/image01.png",
        secondTitle: "tecnologias",
        secondDescription: "Além do ReactJS (aplicação criada com 'create-react-app'), utilizamos JavaScript, Styled Components e CSS em servidor Node.js",
        secondImage: "./assets/img/portfolio/012/image02.png",
        thirdTitle: "ux",
        thirdDescription: "Afim de otimizar a usabilidade do site, incluí um banner com o título do vídeo que é exibido com o 'hover' do mouse, no desktop, e está sempre visível no mobile, além da exibição nativa do vídeo, sem redirecionamento para o site do YouTube.",
        thirdImage: "./assets/img/portfolio/012/image03.png",
        fourthTitle: "responsividade",
        fourthDescription: "O projeto foi estilizado para se adequar a dispositivos móveis, mantendo seu aspecto original e ajustando alguns pontos, como o link 'Novo Vídeo', a fim de garantir uma boa experiência ao usuário.",
        fourthImage: "./assets/img/portfolio/012/image04.png",
        link: 'https://dragonflix.vercel.app/'
    },
    {
        id: "knowleed",
        type: "código",
        stack: "CSS3",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original.svg",
        title: "knowleed",
        description: "Projeto criado durante o Hackathon Mega Hack 3.0 da Shawee, atendendo o desafio da Árvore Educação e alcançando o Top 20 nele.",
        image: "./assets/img/portfolio/011/image01.png",
        secondTitle: "a solução",
        secondDescription: "Uma plataforma de leitura gamificada com sistemas de pontuação, nível, conquistas e ranking, premiando os alunos mais assíduos na plataforma com recompensas no mundo real. Para construir a aplicação, utilizamos HTML, CSS, JavaScript, Node.js, Express e Nunjucks.",
        secondImage: "./assets/img/portfolio/011/image02.png",
        thirdTitle: "o aprendizado",
        thirdDescription: "É fundamental que você tenha um destino para tudo o que for codar. Mesmo que seja pelo aprendizado, é super importante dar um norte ao produto. Se não há um comprador definido, para sua aplicação, dificilmente você vende.<br><br>E nós alcançamos nosso objetivo nesse desafio, com um grande trabalho de pesquisa, ideação, definição de personas, estudo de mercado e entendendo o comportamento de potenciais usuários.",
        thirdImage: "./assets/img/portfolio/011/image03.png",
        fourthTitle: "parceiros de equipe",
        fourthDescription: "Nayra Cruz - UX | Daniel Meiato - PM | Michel Bernardo - Dev | Thiago Pederzolli - Dev",
        fourthImage: "./assets/img/portfolio/011/image04.jpg",
        link: "https://www.youtube.com/watch?v=cAm7oerJ_sY"
    },
    {
        id: "codescola",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "codescola",
        description: "Projeto desenvolvido na segunda edição da NLW, envolvendo React, React Native, Node.js e Typescript. A codEscola é uma plataforma para integrar alunos e professores de programação",
        image: "./assets/img/portfolio/013/image01.png",
        secondTitle: "responsividade",
        secondDescription: "O site foi construído com os princípios do mobile-first, com um design inicialmente voltado para os dispositivos móveis, que se adaptava a grandes telas, através de media queries na estilização dos componentes.",
        secondImage: "./assets/img/portfolio/013/image02.png",
        thirdTitle: "móvel",
        thirdDescription: "E além da aplicação Web, foi desenvolvida uma aplicação móvel, em React Native, permitindo que os alunos pudessem pesquisar os professores disponíveis, inclusive salvando os seus favoritos.",
        thirdImage: "./assets/img/portfolio/013/image03.png",
        fourthTitle: "back-end",
        fourthDescription: "A 'cozinha' da aplicação ficou por conta do TypeScript, que foi usado no template do projeto, além de uma Restful API feita em Node.js, para interface entre os bancos de dados da aplicação e as aplicações web e móvel",
        fourthImage: "./assets/img/portfolio/013/image04.png",
        link: 'https://github.com/euwilliamgoncalves/codescola_webapp_nlw2/'
    },
    {
        id: "ecoleta",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "ecoleta",
        description: "Criado na trilha Starter da primeira #NextLevelWeek da Rocketseat, o Ecoleta é um marketplace de coleta de resíduos. Para esse projeto, utilizamos JavaScript, CSS, HTML, Node.js, Express, Nunjucks e SQLite.",
        image: "./assets/img/portfolio/009/image01.png",
        secondTitle: "busca por localidade",
        secondDescription: "Os pontos cadastrados podem ser encontrados através do link da página principal que redireciona a um modal de busca.",
        secondImage: "./assets/img/portfolio/009/image02.png",
        thirdTitle: "resultados de pesquisa",
        thirdDescription: "A busca retorna em uma página dinâmica, preenchida com os dados do banco de dados (SQLite), através da template engine Nunjucks.",
        thirdImage: "./assets/img/portfolio/009/image03.png",
        fourthTitle: "cadastro dos pontos de coleta",
        fourthDescription: "Os pontos são cadastrados através de formulário que utilizou, inclusive, uma API dos Correios para preenchimento das cidades correspondentes ao estado selecionado. Nessa minha versão, permito a inclusão de novos pontos para teste da plataforma e o servidor Node.js apaga os novos registros, dois minutos após a inclusão.",
        fourthImage: "./assets/img/portfolio/009/image04.png",
        link: "https://euwg-nlw1-ecoleta.glitch.me/"
    },
    {
        id: "bootstrap",
        type: "código",
        stack: "CSS3",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original.svg",
        title: "bootstrap",
        description: "Essa página foi criada para exercitar os conhecimentos adquiridos no curso de Bootstrap da Digital Innovation One, ministrado pelo professor Rafael Galleani.",
        image: "./assets/img/portfolio/010/image01.png",
        secondTitle: "objetivo",
        secondDescription: "Nesse curso, foram abordados os principais recursos desse framework, além de sua aplicação prática criando um site.",
        secondImage: "./assets/img/portfolio/010/image02.png",
        thirdTitle: "meu toque",
        thirdDescription: "A partir disso, criei essa página, buscando apoio na documentação oficial do Bootstrap, para alguns pequenos ajustes, e acrescentando duas fontes do repositório da Google, para customizar a aparência da página.",
        thirdImage: "./assets/img/portfolio/010/image03.png",
        fourthTitle: "sobre o bootstrap",
        fourthDescription: "É um framework para desenvolvimento front-end de páginas web, focado na responsividade do projeto. Utilizando grids, a página pode se adaptar a qualquer tela, ficando mais legível e adequada a cada dispositivo. É um dos recursos mais utilizados para desenvolvimento web, devido a sua flexibilidade e as inúmeras possibilidades de aplicação.",
        fourthImage: "./assets/img/portfolio/010/image04.png",
        link: "https://euwilliamgoncalves.github.io/dio_bootstrap/"
    },
]

export default portfolioList;
