const portfolioList = [
    {
        id: "moovit",
        type: "design",
        stack: "",
        stkimg: "",
        title: "moovit",
        description: "Projeto desenvolvido em parceira para com a Moovit que disponibilizou, em seu aplicativo oficial, um mapa das linhas de transporte em massa da região metropolitana do Rio.",
        image: "/assets/img/portfolio/008/image01.png",
        secondTitle: "rotas na palma da mão",
        secondDescription: "Disponível no app oficial da Moovit, o mapa visava facilitar a vida dos cariocas, dando uma visão detalhada das principais linhas de trem, metrô, brt, etc.",
        secondImage: "/assets/img/portfolio/008/image02.png",
        thirdTitle: "na mídia",
        thirdDescription: "O Jornal O Dia, um dos maiores da região, replicou uma matéria do Diário do Transporte, noticiando a disponibilização desse recurso em Maio de 2017, destacando a parceria entre a Moovit e a Karioka (minha marca, na época).",
        thirdImage: "/assets/img/portfolio/008/image03.png",
        fourthTitle: "do relevante ao essencial",
        fourthDescription: "O mapa destacava, inclusive, as estações que tinham recursos de acessibilidade, visando o conforto e bem estar dos usuários. O mapa ficou disponível durante mais de um ano, até sofrer alterações e ser substituído pelo mapa oficial da Prefeitura do Rio.",
        fourthImage: "/assets/img/portfolio/008/image04.png",
        link: "https://omagotemum.site/assets/files/001.pdf"
    },
    {
        id: "karioka",
        type: "design",
        stack: "",
        stkimg: "",
        title: "karioka",
        description: "Estamparia com temática voltada para a cultura pop do Rio de Janeiro. Foi minha marca por mais de três anos, até o projeto da estamparia ser iniciado.",
        image: "/assets/img/portfolio/001/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando a silhueta do Pão de Açúcar em 'negative space' sobre o círculo azul, que representa o céu.",
        secondImage: "/assets/img/portfolio/001/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Letras desenhadas a partir de linhas e círculos.",
        thirdImage: "/assets/img/portfolio/001/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone15-3919TCX",
        fourthImage: "/assets/img/portfolio/001/image04.png",
        link: ""
    },
    {
        id: "horus",
        type: "design",
        stack: "",
        stkimg: "",
        title: "horus",
        description: "Consultoria em energia, eletricidade e serviços associados.",
        image: "/assets/img/portfolio/002/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando um olho e o bico de um falcão, imagem associada ao deus egípcio Horus.",
        secondImage: "/assets/img/portfolio/002/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Letras desenhadas a partir de linhas e círculos.",
        thirdImage: "/assets/img/portfolio/002/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone18-3838TCX",
        fourthImage: "/assets/img/portfolio/002/image04.png",
        link: ""
    },
    {
        id: "revoar",
        type: "design",
        stack: "",
        stkimg: "",
        title: "revoar",
        description: "Agência de turismo e eventos. O nome é uma analogia ao francês 'revoir', além de significar 'voar de novo' (re-voar).",
        image: "/assets/img/portfolio/003/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando a silhueta da Torre Eiffel, com dois pássaros em sobreposição aos andares da torre, como representação do nome.",
        secondImage: "/assets/img/portfolio/003/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Gruppo Regular",
        thirdImage: "/assets/img/portfolio/003/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone7557C, Pantone1807C, Pantone2727C",
        fourthImage: "/assets/img/portfolio/003/image04.png",
        link: ""
    },
    {
        id: "elevestebem",
        type: "design",
        stack: "",
        stkimg: "",
        title: "ele veste bem",
        description: "Blog de moda.",
        image: "/assets/img/portfolio/004/image01.png",
        secondTitle: "construção",
        secondDescription: "Listras verticais sobrepostas as silhuetas de uma barba e uma gravata borboleta, produtos de desenho digital/vetorial.",
        secondImage: "/assets/img/portfolio/004/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Josefin Sans Light",
        thirdImage: "/assets/img/portfolio/004/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "PantoneBlack7C, Pantone7671C",
        fourthImage: "/assets/img/portfolio/004/image04.png",
        link: ""
    },
    {
        id: "greencoast",
        type: "design",
        stack: "",
        stkimg: "",
        title: "greencoast",
        description: "Serviços em eletricidade, energia, projetos e manutenção.",
        image: "/assets/img/portfolio/005/image01.png",
        secondTitle: "construção",
        secondDescription: "Folha de árvore com nervura em formato de um transistor NPN, representando o ramo de atuação da empresas (energia, eletrônica e eficiência), aplicada em negativo a um círculo, produto de desenho digital/vetorial.",
        secondImage: "/assets/img/portfolio/005/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Exo 2 Light<br>Exo 2 Thin",
        thirdImage: "/assets/img/portfolio/005/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone7489C",
        fourthImage: "/assets/img/portfolio/005/image04.png",
        link: ""
    },
    {
        id: "carregadodeaxe",
        type: "design",
        stack: "",
        stkimg: "",
        title: "carregado de axé",
        description: "Loja virtual de artigos culturais e religiosos (projeto em andamento).",
        image: "/assets/img/portfolio/006/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos. As cores foram inspiradas na bandeira do Estado de Osún, na Nigéria.",
        secondImage: "/assets/img/portfolio/006/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Futurafrica Regular",
        thirdImage: "/assets/img/portfolio/006/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone7533C, Pantone7568C, Pantone7427C, Pantone7743C, Pantone7563C",
        fourthImage: "/assets/img/portfolio/006/image04.png",
        link: ""
    },
    {
        id: "convivencia",
        type: "design",
        title: "convivência",
        description: "Atêlie/projeto cultural formado por artistas portadores da Síndrome de Down.",
        image: "/assets/img/portfolio/007/image01.png",
        secondTitle: "construção",
        secondDescription: "Vetorização e colorização de arte feita por uma das integrantes do projeto.",
        secondImage: "/assets/img/portfolio/007/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "NovaMono Regular",
        thirdImage: "/assets/img/portfolio/007/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "#323F3C, #40534F, #557162, #698F70, #7FAF7F",
        fourthImage: "/assets/img/portfolio/007/image04.png",
        link: ""
    },
    {
        id: "iza",
        type: "código",
        stack: "CSS3",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original.svg",
        title: "iza",
        description: "Fanpage criada com HTML e CSS, utilizando técnicas de CSS Grid e Flexbox, tornando a página totalmente responsiva em diferentes dispositivos.",
        image: "/assets/img/portfolio/015/image01.jpg",
        secondTitle: "discografia",
        secondDescription: "Desde álbuns de estúdios a singles e participações, o site conta com o acervo da cantora, com links para as principais plataformas de streaming.",
        secondImage: "/assets/img/portfolio/015/image02.jpg",
        thirdTitle: "videografia",
        thirdDescription: "A videografia da cantora também está disponível na página, redirecionando o usuário através de um link para o do canal oficial no YouTube.",
        thirdImage: "/assets/img/portfolio/015/image03.jpg",
        fourthTitle: "redes sociais",
        fourthDescription: "A página conta também com os links para as redes sociais da Iza, bem como para seus perfis nas plataformas de streaming.",
        fourthImage: "/assets/img/portfolio/015/image04.jpg",
        link: 'https://iza.now.sh/'
    },
    {
        id: "pedra-papel-tesoura",
        type: "código",
        stack: "Vue.js",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/vuejs/vuejs-original.svg",
        title: "pedra, papel, tesoura",
        description: "Jogo criado durante o Dev Day da Digital Innovation, através das aulas do Rafael Maia, utilizando Vue e Sass, além de recursos como responsividade e um local storage para armazenar a pontuação",
        image: "/assets/img/portfolio/016/image01.jpg",
        secondTitle: "conceito",
        secondDescription: "O jogo é uma variação do clássico Pedra, Papel e Tesoura, com o acréscimo de duas novas jogadas: Lagarto e Spock, que minimizam as chances de empate. Na tela inicial, você conta com os links para jogar e para ver as regras",
        secondImage: "/assets/img/portfolio/016/image02.jpg",
        thirdTitle: "regras",
        thirdDescription: "As regras originais se mantém com uma única diferença: nessa versão, cada jogada pode vencer ou perder de outras duas.",
        thirdImage: "/assets/img/portfolio/016/image03.jpg",
        fourthTitle: "jogabilidade",
        fourthDescription: "O gameplay é descomplicado possibilitando jogadas consecutivas em uma tela com design minimalista e interativo, que garante bons momentos de diversão.",
        fourthImage: "/assets/img/portfolio/016/image04.jpg",
        link: 'https://pptls.now.sh/'
    },
    {
        id: "rmgeradores",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "rm geradores",
        description: "Site institucional da RM Geradores, criado em formato 'one page layout'. A ideia por trás desse trabalho visava criar algo que fosse funcional e passasse uma mensagem rápida e direta, sem tomar muito tempo dos clientes.",
        image: "/assets/img/portfolio/014/image01.png",
        secondTitle: "dinâmico",
        secondDescription: "A seção de serviços conta com um script que exibe de forma dinâmica as informações referentes a cada tópico, sem a necessidade de redirecionar o cliente para outra(s) página(s).",
        secondImage: "/assets/img/portfolio/014/image02.png",
        thirdTitle: "call to action",
        thirdDescription: "Indo contra o usual do segmento, que costuma usar textos estáticos para as informações de contato, a RM conta com botões funcionais que levam os visitantes em contato direto com a equipe.",
        thirdImage: "/assets/img/portfolio/014/image03.png",
        fourthTitle: "mobile-first",
        fourthDescription: "A página foi criada com os princípios de 'mobile-first, para que o uso dela fosse otimizado em dispositivos móveis, melhorando a usabilidade e a experiência dos clientes, parceiros e colaboradores.",
        fourthImage: "/assets/img/portfolio/014/image04.png",
        link: 'https://rmgeradores.com.br/'
    },
    {
        id: "dragonflix",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "dragonflix",
        description: "Projeto criado durante a #ImersãoReact da Alura, que consiste-se em um acervo de vídeos do YouTube escolhidos pelo usuário. Criei o Dragonflix, uma coletânea de vídeos de rock e metal.",
        image: "/assets/img/portfolio/012/image01.png",
        secondTitle: "tecnologias",
        secondDescription: "Além do ReactJS (aplicação criada com 'create-react-app'), utilizamos JavaScript, Styled Components e CSS em servidor Node.js",
        secondImage: "/assets/img/portfolio/012/image02.png",
        thirdTitle: "ux",
        thirdDescription: "Afim de otimizar a usabilidade do site, incluí um banner com o título do vídeo que é exibido com o 'hover' do mouse, no desktop, e está sempre visível no mobile, além da exibição nativa do vídeo, sem redirecionamento para o site do YouTube.",
        thirdImage: "/assets/img/portfolio/012/image03.png",
        fourthTitle: "responsividade",
        fourthDescription: "O projeto foi estilizado para se adequar a dispositivos móveis, mantendo seu aspecto original e ajustando alguns pontos, como o link 'Novo Vídeo', a fim de garantir uma boa experiência ao usuário.",
        fourthImage: "/assets/img/portfolio/012/image04.png",
        link: 'https://dragonflix.vercel.app/'
    },
    {
        id: "knowleed",
        type: "código",
        stack: "CSS3",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original.svg",
        title: "knowleed",
        description: "Projeto criado durante o Hackathon Mega Hack 3.0 da Shawee, atendendo o desafio da Árvore Educação e alcançando o Top 20 nele.",
        image: "/assets/img/portfolio/011/image01.png",
        secondTitle: "a solução",
        secondDescription: "Uma plataforma de leitura gamificada com sistemas de pontuação, nível, conquistas e ranking, premiando os alunos mais assíduos na plataforma com recompensas no mundo real. Para construir a aplicação, utilizamos HTML, CSS, JavaScript, Node.js, Express e Nunjucks.",
        secondImage: "/assets/img/portfolio/011/image02.png",
        thirdTitle: "o aprendizado",
        thirdDescription: "É fundamental que você tenha um destino para tudo o que for codar. Mesmo que seja pelo aprendizado, é super importante dar um norte ao produto. Se não há um comprador definido, para sua aplicação, dificilmente você vende.<br><br>E nós alcançamos nosso objetivo nesse desafio, com um grande trabalho de pesquisa, ideação, definição de personas, estudo de mercado e entendendo o comportamento de potenciais usuários.",
        thirdImage: "/assets/img/portfolio/011/image03.png",
        fourthTitle: "parceiros de equipe",
        fourthDescription: "Nayra Cruz - UX | Daniel Meiato - PM | Michel Bernardo - Dev | Thiago Pederzolli - Dev",
        fourthImage: "/assets/img/portfolio/011/image04.jpg",
        link: "https://www.youtube.com/watch?v=cAm7oerJ_sY"
    },
    {
        id: "codescola",
        type: "código",
        stack: "React",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg",
        title: "codescola",
        description: "Projeto desenvolvido na segunda edição da NLW, envolvendo React, React Native, Node.js e Typescript. A codEscola é uma plataforma para integrar alunos e professores de programação",
        image: "/assets/img/portfolio/013/image01.png",
        secondTitle: "responsividade",
        secondDescription: "O site foi construído com os princípios do mobile-first, com um design inicialmente voltado para os dispositivos móveis, que se adaptava a grandes telas, através de media queries na estilização dos componentes.",
        secondImage: "/assets/img/portfolio/013/image02.png",
        thirdTitle: "móvel",
        thirdDescription: "E além da aplicação Web, foi desenvolvida uma aplicação móvel, em React Native, permitindo que os alunos pudessem pesquisar os professores disponíveis, inclusive salvando os seus favoritos.",
        thirdImage: "/assets/img/portfolio/013/image03.png",
        fourthTitle: "back-end",
        fourthDescription: "A 'cozinha' da aplicação ficou por conta do TypeScript, que foi usado no template do projeto, além de uma Restful API feita em Node.js, para interface entre os bancos de dados da aplicação e as aplicações web e móvel",
        fourthImage: "/assets/img/portfolio/013/image04.png",
        link: 'https://github.com/euwilliamgoncalves/codescola_webapp_nlw2/'
    },
    {
        id: "ecoleta",
        type: "código",
        stack: "JavaScript",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg",
        title: "ecoleta",
        description: "Criado na trilha Starter da primeira #NextLevelWeek da Rocketseat, o Ecoleta é um marketplace de coleta de resíduos. Para esse projeto, utilizamos JavaScript, CSS, HTML, Node.js, Express, Nunjucks e SQLite.",
        image: "/assets/img/portfolio/009/image01.png",
        secondTitle: "busca por localidade",
        secondDescription: "Os pontos cadastrados podem ser encontrados através do link da página principal que redireciona a um modal de busca.",
        secondImage: "/assets/img/portfolio/009/image02.png",
        thirdTitle: "resultados de pesquisa",
        thirdDescription: "A busca retorna em uma página dinâmica, preenchida com os dados do banco de dados (SQLite), através da template engine Nunjucks.",
        thirdImage: "/assets/img/portfolio/009/image03.png",
        fourthTitle: "cadastro dos pontos de coleta",
        fourthDescription: "Os pontos são cadastrados através de formulário que utilizou, inclusive, uma API dos Correios para preenchimento das cidades correspondentes ao estado selecionado. Nessa minha versão, permito a inclusão de novos pontos para teste da plataforma e o servidor Node.js apaga os novos registros, dois minutos após a inclusão.",
        fourthImage: "/assets/img/portfolio/009/image04.png",
        link: "https://euwg-nlw1-ecoleta.glitch.me/"
    },
    {
        id: "bootstrap",
        type: "código",
        stack: "CSS3",
        stkimg: "https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original.svg",
        title: "bootstrap",
        description: "Essa página foi criada para exercitar os conhecimentos adquiridos no curso de Bootstrap da Digital Innovation One, ministrado pelo professor Rafael Galleani.",
        image: "/assets/img/portfolio/010/image01.png",
        secondTitle: "objetivo",
        secondDescription: "Nesse curso, foram abordados os principais recursos desse framework, além de sua aplicação prática criando um site.",
        secondImage: "/assets/img/portfolio/010/image02.png",
        thirdTitle: "meu toque",
        thirdDescription: "A partir disso, criei essa página, buscando apoio na documentação oficial do Bootstrap, para alguns pequenos ajustes, e acrescentando duas fontes do repositório da Google, para customizar a aparência da página.",
        thirdImage: "/assets/img/portfolio/010/image03.png",
        fourthTitle: "sobre o bootstrap",
        fourthDescription: "É um framework para desenvolvimento front-end de páginas web, focado na responsividade do projeto. Utilizando grids, a página pode se adaptar a qualquer tela, ficando mais legível e adequada a cada dispositivo. É um dos recursos mais utilizados para desenvolvimento web, devido a sua flexibilidade e as inúmeras possibilidades de aplicação.",
        fourthImage: "/assets/img/portfolio/010/image04.png",
        link: "https://euwilliamgoncalves.github.io/dio_bootstrap/"
    },
]

export default portfolioList;