const portfolioList = [
    {
        id: "0",
        type: "design",
        title: "karioka | logo",
        description: "Estamparia com temática voltada para a cultura pop do Rio de Janeiro. Foi minha marca por mais de três anos, até o projeto da estamparia ser iniciado.",
        image: "/assets/img/portfolio/001/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando a silhueta do Pão de Açúcar em 'negative space' sobre o círculo azul, que representa o céu.",
        secondImage: "/assets/img/portfolio/001/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Letras desenhadas a partir de linhas e círculos.",
        thirdImage: "/assets/img/portfolio/001/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone 15-3919 TCX - Serenity (Cor do Ano de 2016)",
        fourthImage: "/assets/img/portfolio/001/image04.png",
        link: ""
    },
    {
        id: "1",
        type: "design",
        title: "horus | logo",
        description: "Consultoria em energia, eletricidade e serviços associados.",
        image: "/assets/img/portfolio/002/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando um olho e o bico de um falcão, imagem associada ao deus egípcio Horus.",
        secondImage: "/assets/img/portfolio/002/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Letras desenhadas a partir de linhas e círculos.",
        thirdImage: "/assets/img/portfolio/002/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone 18-3838 TCX - Ultra Violet (Cor do Ano de 2018)",
        fourthImage: "/assets/img/portfolio/002/image04.png",
        link: ""
    },
    {
        id: "2",
        type: "design",
        title: "revoar | naming e logo",
        description: "Agência de turismo e eventos. O nome é uma analogia ao francês 'revoir', além de significar 'voar de novo' (re-voar).",
        image: "/assets/img/portfolio/003/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos, formando a silhueta da Torre Eiffel, com dois pássaros em sobreposição aos andares da torre, como representação do nome.",
        secondImage: "/assets/img/portfolio/003/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Gruppo Regular",
        thirdImage: "/assets/img/portfolio/003/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone 7557 C<br>Pantone 1807 C<br>Pantone 2727 C",
        fourthImage: "/assets/img/portfolio/003/image04.png",
        link: ""
    },
    {
        id: "3",
        type: "design",
        title: "ele veste bem | logo",
        description: "Blog de moda.",
        image: "/assets/img/portfolio/004/image01.png",
        secondTitle: "construção",
        secondDescription: "Listras verticais sobrepostas as silhuetas de uma barba e uma gravata borboleta, produtos de desenho digital/vetorial.",
        secondImage: "/assets/img/portfolio/004/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Josefin Sans Light",
        thirdImage: "/assets/img/portfolio/004/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone Black 7 C<br>Pantone 7671 C",
        fourthImage: "/assets/img/portfolio/004/image04.png",
        link: ""
    },
    {
        id: "4",
        type: "design",
        title: "greencoast | logo",
        description: "Serviços em eletricidade, energia, projetos e manutenção.",
        image: "/assets/img/portfolio/005/image01.png",
        secondTitle: "construção",
        secondDescription: "Folha de árvore com nervura em formato de um transistor NPN, representando o ramo de atuação da empresas (energia, eletrônica e eficiência), aplicada em negativo a um círculo, produto de desenho digital/vetorial.",
        secondImage: "/assets/img/portfolio/005/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Exo 2 Light<br>Exo 2 Thin",
        thirdImage: "/assets/img/portfolio/005/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone 7489 C",
        fourthImage: "/assets/img/portfolio/005/image04.png",
        link: ""
    },
    {
        id: "5",
        type: "design",
        title: "carregado de axé | logo",
        description: "Loja virtual de artigos culturais e religiosos (projeto em andamento).",
        image: "/assets/img/portfolio/006/image01.png",
        secondTitle: "construção",
        secondDescription: "Ícone baseado em círculos. As cores foram inspiradas na bandeira do Estado de Osún, na Nigéria.",
        secondImage: "/assets/img/portfolio/006/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "Futurafrica Regular",
        thirdImage: "/assets/img/portfolio/006/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "Pantone 7533 C<br>Pantone 7568 C<br>Pantone 7427 C<br>Pantone 7743 C<br>Pantone 7563 C",
        fourthImage: "/assets/img/portfolio/006/image04.png",
        link: ""
    },
    {
        id: "6",
        type: "design",
        title: "convivência | logo",
        description: "Atêlie/projeto cultural formado por artistas portadores da Síndrome de Down.",
        image: "/assets/img/portfolio/007/image01.png",
        secondTitle: "construção",
        secondDescription: "Vetorização e colorização de arte feita por uma das integrantes do projeto.",
        secondImage: "/assets/img/portfolio/007/image02.png",
        thirdTitle: "tipografia",
        thirdDescription: "NovaMono Regular",
        thirdImage: "/assets/img/portfolio/007/image03.png",
        fourthTitle: "paleta de cores",
        fourthDescription: "#323F3C #40534F #557162 #698F70 #7FAF7F",
        fourthImage: "/assets/img/portfolio/007/image04.png",
        link: ""
    },
    {
        id: "7",
        type: "design",
        title: "moovit | mapa RJ (2017)",
        description: "Projeto desenvolvido em parceira para com a Moovit que disponibilizou, em seu aplicativo oficial, um mapa das linhas de transporte em massa da região metropolitana do Rio.",
        image: "/assets/img/portfolio/008/image01.png",
        secondTitle: "rotas na palma da mão",
        secondDescription: "Disponível no app oficial da Moovit, o mapa visava facilitar a vida dos cariocas, dando uma visão detalhada das principais linhas de trem, metrô, brt, etc.",
        secondImage: "/assets/img/portfolio/008/image02.png",
        thirdTitle: "na mídia",
        thirdDescription: "O Jornal O Dia, um dos maiores da região, replicou uma matéria do Diário do Transporte, noticiando a disponibilização desse recurso em Maio de 2017, destacando a parceria entre a Moovit e a Karioka (minha marca, na época).",
        thirdImage: "/assets/img/portfolio/008/image03.png",
        fourthTitle: "do relevante ao essencial",
        fourthDescription: "O mapa destacava, inclusive, as estações que tinham recursos de acessibilidade, visando o conforto e bem estar dos usuários. O mapa ficou disponível durante mais de um ano, até sofrer alterações e ser substituído pelo mapa oficial da Prefeitura do Rio.",
        fourthImage: "/assets/img/portfolio/008/image04.png",
        link: "assets/files/001.pdf"
    },
    {
        id: "8",
        type: "código",
        title: "ecoleta | site",
        description: "Criado na trilha Starter da primeira #NextLevelWeek da Rocketseat, o Ecoleta é um marketplace de coleta de resíduos. Para esse projeto, utilizamos JavaScript, CSS, HTML, Node.js, Express, Nunjucks e SQLite.",
        image: "/assets/img/portfolio/009/image01.png",
        secondTitle: "busca por localidade",
        secondDescription: "Os pontos cadastrados podem ser encontrados através do link da página principal que redireciona a um modal de busca.",
        secondImage: "/assets/img/portfolio/009/image02.png",
        thirdTitle: "resultados de pesquisa",
        thirdDescription: "A busca retorna em uma página dinâmica, preenchida com os dados do banco de dados (SQLite), através da template engine Nunjucks.",
        thirdImage: "/assets/img/portfolio/009/image03.png",
        fourthTitle: "cadastro dos pontos de coleta",
        fourthDescription: "Os pontos são cadastrados através de formulário que utilizou, inclusive, uma API dos Correios para preenchimento das cidades correspondentes ao estado selecionado. Nessa minha versão, permito a inclusão de novos pontos para teste da plataforma e o servidor Node.js apaga os novos registros, dois minutos após a inclusão.",
        fourthImage: "/assets/img/portfolio/009/image04.png",
        link: "https://euwg-nlw1-ecoleta.glitch.me/"
    },
    {
        id: "9",
        type: "código",
        title: "bootstrap | site",
        description: "Essa página foi criada para exercitar os conhecimentos adquiridos no curso de Bootstrap da Digital Innovation One, ministrado pelo professor Rafael Galleani.",
        image: "/assets/img/portfolio/010/image01.png",
        secondTitle: "objetivo",
        secondDescription: "Nesse curso, foram abordados os principais recursos desse framework, além de sua aplicação prática criando um site.",
        secondImage: "/assets/img/portfolio/010/image02.png",
        thirdTitle: "meu toque",
        thirdDescription: "A partir disso, criei essa página, buscando apoio na documentação oficial do Bootstrap, para alguns pequenos ajustes, e acrescentando duas fontes do repositório da Google, para customizar a aparência da página.",
        thirdImage: "/assets/img/portfolio/010/image03.png",
        fourthTitle: "sobre o bootstrap",
        fourthDescription: "É um framework para desenvolvimento front-end de páginas web, focado na responsividade do projeto. Utilizando grids, a página pode se adaptar a qualquer tela, ficando mais legível e adequada a cada dispositivo. É um dos recursos mais utilizados para desenvolvimento web, devido a sua flexibilidade e as inúmeras possibilidades de aplicação.",
        fourthImage: "/assets/img/portfolio/010/image04.png",
        link: "https://euwilliamgoncalves.github.io/dio_bootstrap/"
    },
    {
        id: "10",
        type: "código",
        title: "knowleed | projeto mega hack 3.0",
        description: "Projeto criado durante o Hackathon Mega Hack 3.0 da Shawee, atendendo o desafio da Árvore Educação e alcançando o Top 20 nele.",
        image: "/assets/img/portfolio/011/image01.png",
        secondTitle: "a solução",
        secondDescription: "Uma plataforma de leitura gamificada com sistemas de pontuação, nível, conquistas e ranking, premiando os alunos mais assíduos na plataforma com recompensas no mundo real. Para construir a aplicação, utilizamos HTML, CSS, JavaScript, Node.js, Express e Nunjucks.",
        secondImage: "/assets/img/portfolio/011/image02.png",
        thirdTitle: "o aprendizado",
        thirdDescription: "É fundamental que você tenha um destino para tudo o que for codar. Mesmo que seja pelo aprendizado, é super importante dar um norte ao produto. Se não há um comprador definido, para sua aplicação, dificilmente você vende.<br><br>E nós alcançamos nosso objetivo nesse desafio, com um grande trabalho de pesquisa, ideação, definição de personas, estudo de mercado e entendendo o comportamento de potenciais usuários.",
        thirdImage: "/assets/img/portfolio/011/image03.png",
        fourthTitle: "parceiros de equipe",
        fourthDescription: "Nayra Cruz - UX | Daniel Meiato - PM | Michel Bernardo - Dev | Thiago Pederzolli - Dev",
        fourthImage: "/assets/img/portfolio/011/image04.jpg",
        link: "https://www.youtube.com/watch?v=cAm7oerJ_sY"
    },
    {
        id: "11",
        type: "código",
        title: "dragonflix | #ImersãoReact",
        description: "Projeto criado durante a #ImersãoReact da Alura, que consiste-se em um acervo de vídeos do YouTube escolhidos pelo usuário. Criei o Dragonflix, uma coletânea de vídeos de rock e metal.",
        image: "/assets/img/portfolio/012/image01.png",
        secondTitle: "tecnologias",
        secondDescription: "Além do ReactJS (aplicação criada com 'create-react-app'), utilizamos JavaScript, Styled Components e CSS em servidor Node.js",
        secondImage: "/assets/img/portfolio/012/image02.png",
        thirdTitle: "ux",
        thirdDescription: "Afim de otimizar a usabilidade do site, incluí um banner com o título do vídeo que é exibido com o 'hover' do mouse, no desktop, e está sempre visível no mobile, além da exibição nativa do vídeo, sem redirecionamento para o site do YouTube.",
        thirdImage: "/assets/img/portfolio/012/image03.png",
        fourthTitle: "responsividade",
        fourthDescription: "O projeto foi estilizado para se adequar a dispositivos móveis, mantendo seu aspecto original e ajustando alguns pontos, como o link 'Novo Vídeo', a fim de garantir uma boa experiência ao usuário.",
        fourthImage: "/assets/img/portfolio/012/image04.png",
        link: 'https://dragonflix.vercel.app/'
    },
]

export default portfolioList;